cluster: &CLUSTER_NAME tmas

librarian:
  server:
    host: 16.25.153.89
    install: 
      prefix: /var/tmp/lfs
      modules:
        tm_librarian: tm-librarian
        tm_ivshmem_server: tm-ivshmem-server

  clients:
    cluster: *CLUSTER_NAME
    install: 
      prefix: /root/l4tm
      modules:
        tm_librarian: tm-librarian
        zbridge_driver: zbridge_driver
        tm_fuse: tm-fuse-4.3.3
        tm_libfuse: tm-libfuse

  ini_file: l4tm_book_data.tmas.ini

  git_repo:
    local:
      /tmp/lfs-repo
      
    latest:
    - https://github.hpe.com/hpelinux/tm-librarian.git
    - https://github.hpe.com/hpelinux/tm-ivshmem-server.git
    - https://github.hpe.com/hpelinux/zbridge_driver.git
    - https://github.hpe.com/hpelinux/tm-fuse-4.3.3.git
    - https://github.hpe.com/hpelinux/tm-libfuse.git:
        branch: 'hp_l4tm'

    stable:
    - https://github.hpe.com/hpelinux/tm-librarian.git:
        tag: '64dc22ac38b5966b93342b2d80ad7877ac4f5d51'
    - https://github.hpe.com/hpelinux/tm-ivshmem-server.git:
        tag: 'fc58e340db7f0b680eec248e1121a2ada674e122'
    - https://github.hpe.com/hpelinux/zbridge_driver.git:
        tag: '157786fe0bbf529fc6145a938bdd373ff4295300'
    - https://github.hpe.com/hpelinux/tm-fuse-4.3.3.git:
        tag: 'b4d4dd00f8ccc431501af36f08e797b4fed0c1f7'
    - https://github.hpe.com/hpelinux/tm-libfuse.git:
        branch: 'hp_l4tm'
        tag: '386b1b6e3d0fcf7e2dfd5473e867284410dfa624'
